### ISSUE TITLE
Recurring events duplicated a ridiculous number of times

### ISSUE THREAD

**Issue by newsch** [olinlibrary/ABE#126]
![image](https://user-images.githubusercontent.com/10699964/38536780-fa9da12e-3c58-11e8-8d00-e57897529b26.png)

the event info in mongodb:
```javascript
{
  "_id": ObjectId("5acc3e54db9fbc000b2b0d6b"),
  "_cls": "Event",
  "title": "Talk about recurrences",
  "labels": [
    "library",
    "featured"
  ],
  "visibility": "olin",
  "start": ISODate("2018-04-10T07:20:47Z"),
  "end": ISODate("2018-04-10T09:00:47Z"),
  "allDay": false,
  "recurrence": {
    "frequency": "WEEKLY",
    "interval": "1",
    "by_day": [
      "MO",
      "TH"
    ],
    "by_month_day": [ ],
    "by_month": [ ],
    "by_year_day": [ ],
    "forever": false
  },
  "recurrence_end": ISODate("9999-12-31T03:20:47Z"),
  "sub_events": [ ]
}
```
It was created through the frontend, and I think the problem may be related to the `forever` field being `false` and the `recurrence_end` field being set to the end of time.

**Comment by mpbrucker** [comment]
I wasn't able to replicate this through the frontend, so I believe if may have been restricted to the frontend and fixed already. However, it did highlight some strange handling of recurrent events. I expected this event to cause an issue since in the [recurrence expansion](https://github.com/olinlibrary/ABE/blob/23dd768e7a25af8526ee0b98a1456fbc6c34787a/abe/helper_functions/sub_event_helpers.py#L178) it's supposed to fully expand events if they don't occur forever, so it should enumerate every occurrence until the year 9999. However, it appears to be checking for an `until` field, but not a `recurrence_end` field. So, it seems like there might be two things here: not fully expanding really long recurrent events, and standardizing which field is used to check for the recurrence end.

**Comment by mpbrucker** [comment]
After looking in the dev database, it appears that this event is just duplicated several times in the dev database.

**Comment by mpbrucker** [comment]
Duplicate events have been removed from the database.
