### ISSUE TITLE
Call to `rrule` with inconsistent arguments

### ISSUE THREAD

**Issue by osteele** [olinlibrary/ABE#177]
```shell
$ python -m unittest tests/test_recurrences.py
INFO:root:Using db "abe-unittest" with localhost
/Users/osteele/code/htl2/ABE/.direnv/python-3.6.5/lib/python3.6/site-packages/dateutil/rrule.py:468: DeprecationWarning: Using both 'count' and 'until' is inconsistent with RFC 5545 and has been deprecated in dateutil. Future versions will raise an error.
  "raise an error.", DeprecationWarning)
```

In addition to a pending error (when `dateutil` is upgraded), this probably means the code is not doing what we think it is. It's also a [broken window](https://blog.codinghorror.com/the-broken-window-theory/).

The culprit is `sub_event_helpers.py#181-2`:

```python
     rule_list = list(rrule(freq=rFrequency, count=rCount, interval=rInterval, until=rUntil, bymonth=rByMonth, \
        bymonthday=rByMonthDay, byweekday=rByDay, dtstart=rStart))
```

**Comment by mpbrucker** [comment]
I set up a [branch](https://github.com/olinlibrary/ABE/tree/mpb/rrule_fix) to fix this issue - according to the iCal spec, COUNT and UNTIL shouldn't both be provided. As a simple fix, I modified it to only include COUNT if UNTIL is none. I did also have to modify some tests in `test_recurrence.py` since this is slightly changing the behavior of recurrent event creation to prioritize UNTIL over COUNT, but it probably won't impact a whole lot since events created from the web calendar shouldn't have both anyway.
