### ISSUE TITLE
Label visibility default values

### ISSUE THREAD

**Issue by kylecombes** [olinlibrary/ABE#83]
## Current behavior
  * When a label defaults to visible, `default: "True"` (string)
  * When a label defaults to invisible, `default` is undefined

## Desired behavior
  * When a label defaults to visible, `visible: true` (boolean)
  * When a label defaults to invisible, `visible: false`

**Comment by newsch** [comment]
Neat! This was a three-part bug:
- the `default` field for labels wasn't set as required
- the `mongo_to_dict` function was returning strings of BooleanFields
- the `mongo_to_dict` function wasn't checking to see if fields existed in dictionary correctly - checking `obj[field_name]` rather than `field_name in obj`, so if the value of `obj[field_name]` was `False` the check for the field returned `False`
